"""
investigation/nodes/report.py
===============================
LangGraph node: Report

Drafts a formal bilingual SAR (Suspicious Activity Report) in:
  • English  — FinCEN Form 111 structure (US standard)
  • French   — TRACFIN CERFA 10534 structure (French FIU standard)

Two-Pass Generation Strategy
-------------------------------
  Pass 1 (English): Full SAR narrative generated with all context.
  Pass 2 (French):  English narrative is translated + adapted for TRACFIN
                    structure, NOT independently re-generated.
                    This avoids hallucination divergence between versions.

Self-Critique Guard (NeMo Guardrails)
--------------------------------------
  After each generation pass, the output rails check that:
  • No legal statute is cited that isn't in the approved whitelist.
  • No hallucinated transaction amounts (all amounts must appear in the
    context; the guardrail runs a regex comparison against known values).
  • The SAR has mandatory fields: subject, activity description,
    reporting entity, narrative, and law enforcement contact fields.
  If any check fails, the node returns with `sar_report.status = DRAFT`
  and adds the violation to `guardrail_violations` for analyst review.

SAR Structure (FinCEN Form 111 alignment)
------------------------------------------
  Part I   — Subject Information (from KYC chunks)
  Part II  — Suspicious Activity Information (typology, dates, amounts)
  Part III — Narrative (free-text, generated by LLM)
  Part IV  — Filing Institution Information (static config)
"""

from __future__ import annotations

import json
import logging
import re
import uuid
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional

from investigation.state import AMLState, SARReport

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# SAR prompt templates
# ---------------------------------------------------------------------------

SAR_SYSTEM_PROMPT_EN = """You are a certified AML compliance officer drafting a
Suspicious Activity Report (SAR) for submission to FinCEN (Form 111).

MANDATORY RULES:
1. Structure the narrative in 4 sections:
   [SUBJECT] [ACTIVITY] [EVIDENCE] [RECOMMENDATION]
2. Only cite statutes from the approved list:
   31 CFR §1020.320, Bank Secrecy Act (31 USC §5318),
   FATF Recommendations 1, 10, 16, 20, 29, 40.
3. Do NOT fabricate transaction amounts, dates, or counterparty names
   not present in the provided evidence.
4. Write in formal legal English. Maximum 600 words.
5. End with: "This SAR is filed in accordance with 31 CFR §1020.320."
"""

SAR_SYSTEM_PROMPT_FR = """Vous êtes un responsable conformité AML certifié rédigeant
une Déclaration de Soupçon (DS) destinée à TRACFIN (CERFA 10534).

RÈGLES OBLIGATOIRES:
1. Structurez le récit en 4 sections:
   [SUJET] [ACTIVITÉ] [PREUVES] [RECOMMANDATION]
2. Ne citez que les textes juridiques approuvés:
   Code Monétaire et Financier Art. L561-15,
   Directive UE AMLD6 (2018/1673),
   Recommandations GAFI 1, 10, 16, 20, 29, 40.
3. Ne fabriquez aucun montant, date ou contrepartie absent des éléments fournis.
4. Rédigez en français juridique formel. Maximum 600 mots.
5. Terminez par: "Cette déclaration est déposée conformément à l'article L561-15 du CMF."
"""

SAR_HUMAN_TEMPLATE_EN = """
## SAR Draft Request

Account ID  : {node_id}
Risk Score  : {risk_score:.3f}
Risk Level  : {risk_level}
Verdict     : {risk_verdict}
Typologies  : {typologies}
Rule Hits   : {rule_hits}

### Analyst Risk Rationale
{risk_rationale}

### KYC Evidence
{kyc_evidence}

### Adverse Media Evidence
{news_evidence}

### Graph Topology Signals
{graph_summary}

### Similar Past SAR Cases (style reference)
{similar_sars}

Draft the SAR narrative now.
"""

SAR_HUMAN_TEMPLATE_FR = """
## Demande de Rédaction de Déclaration de Soupçon

Numéro de compte : {node_id}
Score de risque  : {risk_score:.3f}
Niveau de risque : {risk_level}
Verdict          : {risk_verdict}
Typologies       : {typologies}

### Justification de l'analyste
{risk_rationale}

### Éléments KYC
{kyc_evidence}

### Médias défavorables
{news_evidence}

### Résumé de la topologie du graphe
{graph_summary}

Traduisez et adaptez la version anglaise ci-dessous pour TRACFIN:

### Narrative anglaise de référence
{english_narrative}

Rédigez maintenant la déclaration de soupçon en français.
"""


# ---------------------------------------------------------------------------
# Report node
# ---------------------------------------------------------------------------

class ReportNode:
    """
    LangGraph node: Generates bilingual SAR (EN + FR) using NIM LLM.

    Two-pass generation with NeMo Guardrails on both passes.
    """

    def __init__(
        self,
        llm: Any,                     # LangChain BaseChatModel
        guardrails: Optional[Any],    # nemoguardrails.LLMRails or None
        reporting_institution: str = "AML Compliance Dept.",
        max_evidence_chars: int = 2000,
    ) -> None:
        self.llm = llm
        self.guardrails = guardrails
        self.reporting_institution = reporting_institution
        self.max_evidence_chars = max_evidence_chars

    # ------------------------------------------------------------------
    # LangGraph callable
    # ------------------------------------------------------------------

    async def __call__(self, state: AMLState) -> Dict[str, Any]:
        """Generate bilingual SAR report and return updated state."""
        node_id = state["node_id"]
        logger.info("[report] Drafting bilingual SAR for node=%s", node_id)

        # Pass 1: English narrative
        en_prompt = self._build_prompt_en(state)
        narrative_en, violations_en = await self._generate(
            en_prompt, SAR_SYSTEM_PROMPT_EN, lang="EN"
        )

        # Pass 2: French narrative (translation of English + TRACFIN adaptation)
        fr_prompt = self._build_prompt_fr(state, narrative_en)
        narrative_fr, violations_fr = await self._generate(
            fr_prompt, SAR_SYSTEM_PROMPT_FR, lang="FR"
        )

        all_violations = violations_en + violations_fr
        status = "DRAFT" if all_violations else "PENDING_REVIEW"

        sar: SARReport = {
            "report_id": f"SAR-{uuid.uuid4().hex[:12].upper()}",
            "node_id":   node_id,
            "risk_score": state["risk_score"],
            "typologies": [
                t for t, s in state["typology_scores"].items() if s >= 0.4
            ],
            "narrative_en":  narrative_en,
            "narrative_fr":  narrative_fr,
            "evidence_refs": self._collect_evidence_refs(state),
            "analyst_notes": state.get("human_feedback") or "",
            "status":        status,
        }

        logger.info(
            "[report] SAR %s generated | status=%s | violations=%d",
            sar["report_id"], status, len(all_violations),
        )

        return {
            "sar_report": sar,
            "guardrail_violations": all_violations,
            "messages": [
                {
                    "role": "assistant",
                    "content": (
                        f"[report] SAR {sar['report_id']} drafted. "
                        f"Status: {status}. Violations: {len(all_violations)}."
                    ),
                }
            ],
        }

    # ------------------------------------------------------------------
    # Prompt builders
    # ------------------------------------------------------------------

    def _build_prompt_en(self, state: AMLState) -> str:
        typologies = [t for t, s in state["typology_scores"].items() if s >= 0.4]
        return SAR_HUMAN_TEMPLATE_EN.format(
            node_id=state["node_id"],
            risk_score=state["risk_score"],
            risk_level=state.get("risk_level", "HIGH"),
            risk_verdict=state.get("risk_verdict", "VERIFIED"),
            typologies=", ".join(typologies) or "Unknown",
            rule_hits=", ".join(state.get("rule_hits", [])) or "None identified",
            risk_rationale=state.get("risk_rationale", "")[:800],
            kyc_evidence=self._format_chunks(state.get("kyc_chunks", []))[: self.max_evidence_chars],
            news_evidence=self._format_chunks(state.get("news_chunks", []))[: self.max_evidence_chars],
            graph_summary=state.get("graph_summary", "")[:500],
            similar_sars=self._format_sars(state.get("similar_sars", []))[:1000],
        )

    def _build_prompt_fr(self, state: AMLState, english_narrative: str) -> str:
        typologies = [t for t, s in state["typology_scores"].items() if s >= 0.4]
        return SAR_HUMAN_TEMPLATE_FR.format(
            node_id=state["node_id"],
            risk_score=state["risk_score"],
            risk_level=state.get("risk_level", "HIGH"),
            risk_verdict=state.get("risk_verdict", "VERIFIED"),
            typologies=", ".join(typologies) or "Inconnu",
            risk_rationale=state.get("risk_rationale", "")[:600],
            kyc_evidence=self._format_chunks(state.get("kyc_chunks", []))[: self.max_evidence_chars],
            news_evidence=self._format_chunks(state.get("news_chunks", []))[: self.max_evidence_chars],
            graph_summary=state.get("graph_summary", "")[:400],
            english_narrative=english_narrative[:1200],
        )

    # ------------------------------------------------------------------
    # LLM generation with Guardrails
    # ------------------------------------------------------------------

    async def _generate(
        self,
        human_prompt: str,
        system_prompt: str,
        lang: str,
    ):
        """Run one generation pass through NeMo Guardrails + LLM."""
        messages = [
            {"role": "system", "content": system_prompt},
            {"role": "user",   "content": human_prompt},
        ]
        violations: List[str] = []

        if self.guardrails is not None:
            try:
                text = await self.guardrails.generate_async(messages=messages)
            except Exception as exc:
                v = f"[{lang}] Guardrail violation: {exc}"
                logger.warning("[report] %s", v)
                violations.append(v)
                text = f"[SAR DRAFT BLOCKED BY GUARDRAIL — {lang}]\n{exc}"
        else:
            resp = await self.llm.ainvoke(messages)
            text = resp.content if hasattr(resp, "content") else str(resp)

        # Post-generation statute validation (lightweight regex guard)
        statute_violations = self._check_hallucinated_statutes(text, lang)
        violations.extend(statute_violations)

        return text, violations

    # ------------------------------------------------------------------
    # Statute hallucination check
    # ------------------------------------------------------------------

    # Approved statute patterns (extend this whitelist as needed)
    _APPROVED_STATUTES = re.compile(
        r"31\s+CFR\s+§?1020|BSA|31\s+USC\s+§?5318|"
        r"FATF\s+Rec|L561-\d+|AMLD[56]|Directive\s+201[58]/\d+|"
        r"Wolfsberg|Basel\s+AML",
        re.IGNORECASE,
    )
    # Pattern to catch things that LOOK like statute references
    _STATUTE_PATTERN = re.compile(
        r"\b(?:§|Art\.|Article|Section|Sec\.|Regulation|Directive|CFR|USC|CMF)\s*[\d\-\.]+",
        re.IGNORECASE,
    )

    def _check_hallucinated_statutes(self, text: str, lang: str) -> List[str]:
        """
        Find all statute-like references in the text and flag any
        that do NOT match the approved whitelist pattern.
        """
        violations = []
        for match in self._STATUTE_PATTERN.finditer(text):
            citation = match.group(0)
            if not self._APPROVED_STATUTES.search(citation):
                v = f"[{lang}] Potential hallucinated statute: {citation!r}"
                logger.warning("[report] %s", v)
                violations.append(v)
        return violations

    # ------------------------------------------------------------------
    # Evidence helpers
    # ------------------------------------------------------------------

    @staticmethod
    def _format_chunks(chunks: list) -> str:
        if not chunks:
            return "No documents available."
        return "\n\n".join(
            f"[{i+1}] (score={c['score']:.3f}) {c['content'][:400]}"
            for i, c in enumerate(chunks)
        )

    @staticmethod
    def _format_sars(sars: list) -> str:
        if not sars:
            return "No similar cases found."
        return "\n\n".join(
            f"[Case {i+1} | typology={c['metadata'].get('typology','?')}]\n"
            f"{c['content'][:400]}"
            for i, c in enumerate(sars)
        )

    @staticmethod
    def _collect_evidence_refs(state: AMLState) -> List[str]:
        """Collect doc_ids from all retrieved chunks as evidence references."""
        refs = []
        for chunk_list in [
            state.get("kyc_chunks", []),
            state.get("news_chunks", []),
            state.get("similar_sars", []),
        ]:
            refs.extend(c["doc_id"] for c in chunk_list)
        return list(dict.fromkeys(refs))  # deduplicate, preserve order
